FinalProject.UI/Models/ErrorViewModel.cs
using System;

namespace FinalProject.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FinalProject.UI/Controllers/AuthenticateController.cs
using Core.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject.UI.Controllers
{
    public class AuthenticateController : Controller
    {
        private readonly IAuthenticate _IAuthenticateRepository;
        public AuthenticateController(IAuthenticate authenticateRepository)
        {
            _IAuthenticateRepository = authenticateRepository;
        }
        public IActionResult Index()
        {
            return View("~/Views/Authenticate/Login.cshtml");
        }

        [HttpPost]
        public async Task<IActionResult> LoginUser(AuthenticateModel model)
        {
            var response = await _IAuthenticateRepository.IsAuthenticate(model);
            if (response)
            {
                HttpContext.Session.SetString("Username", model.UserName);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Index", "Authenticate");
            }
        }
    }
}

FinalProject.UI/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Repository;
using Core.Entity;

namespace FinalProject.UI.Controllers
{

    public class EmployeeController : Controller
    {
        private readonly IEmployeeRepository _IEmployeeRepository;

        public EmployeeController(IEmployeeRepository employeeRepository)
        {
            _IEmployeeRepository = employeeRepository;
        }

        public IActionResult Index(int Id)
        {
            if (Id == 0)
            {
                return View("~/Views/Employee/CreateEmployee.cshtml");
            }
            else
            {
                var response = _IEmployeeRepository.GetEmployeeById(Id);
                return View("~/Views/Employee/CreateEmployee.cshtml", response);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CreateEmployee(Employee model)
        
        {

            if (model.Id == 0)
            {

                var response = await _IEmployeeRepository.CreateEmployee(model);
            }
            else
            {
                var response = await _IEmployeeRepository.UpdateEmployee(model);
            }
            return RedirectToAction("GetEmployee", "Employee");
        }
        public async Task<IActionResult> DeleteEmployee(int Id)
        {
            var response = await _IEmployeeRepository.DeleteEmployee(Id);
            return Json(response);
        }
        public async Task<IActionResult> GetEmployee()
        
        {
            var response = await _IEmployeeRepository.GetEmployee();
            return View("~/Views/Employee/EmployeeList.cshtml", response);
        }
    }
}

FinalProject.UI/Controllers/HomeController.cs
using FinalProject.UI.Helper;
using FinalProject.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject.UI.Controllers
{
    [CustomAuthenticate]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FinalProject.UI/Controllers/UserDetailController.cs
using Core.Entity;
using Microsoft.AspNetCore.Mvc;
using Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject.UI.Controllers
{
    public class UserDetailController : Controller
    {
        private readonly IAuthenticate _IAuthenticateRepository;
        public UserDetailController(IAuthenticate authenticateRepository)
        {
            _IAuthenticateRepository = authenticateRepository;
        }
        public IActionResult Index()
        {
            return View("~/Views/Authenticate/CreateUserDetail.cshtml");
        }
        public async Task<IActionResult> CreateUser(AuthenticateModel model)
        {
            var response = await _IAuthenticateRepository.CreateUser(model);
            return Json(response);
        }
    }
}

FinalProject.UI/Views/Authenticate/CreateUserDetail.cshtml
@model Core.Entity.AuthenticateModel

<div class="container">
    <div class="panel">
        <div class="panel-header">
            Create User
        </div>
        <div class="panel-body">
            <form asp-controller="UserDetail" asp-action="CreateUser">
                <div class="col-md-12">
                    <div class="form-group col-md-4">
                        <label for="email">User Name:</label>
                        <input class="form-control" asp-for="UserName">
                        <span class="text-danger" asp-validation-for="UserName"></span>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="pwd">Password:</label>
                        <input class="form-control" asp-for="Password">
                        <span asp-validation-for="Password"></span>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="pwd">Confirm Password:</label>
                        <input class="form-control" asp-for="ConfirmPassword">
                        <span asp-validation-for="ConfirmPassword"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <button class="btn btn-primary float-right">Save</button>
                </div>

            </form>
        </div>
    </div>

</div>

FinalProject.UI/Views/Authenticate/Login.cshtml
@{Layout = null; }
@model Core.Entity.AuthenticateModel

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Login Form
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</head>
<style>
    html {
        height: 100%;
    }

    body {
        height: 100%;
    }

    .global-container {
        height: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
        background-color: #f5f5f5;
    }

    form {
        padding-top: 10px;
        font-size: 14px;
        margin-top: 30px;
    }

    .card-title {
        font-weight: 300;
    }

    .btn {
        font-size: 14px;
        margin-top: 20px;
    }

    .login-form {
        width: 330px;
        margin: 20px;
    }

    .sign-up {
        text-align: center;
        padding: 20px 0 0;
    }

    .alert {
        margin-bottom: -30px;
        font-size: 13px;
        margin-top: 20px;
    }
</style>
<body>
    <div class="pt-5">
        <div class="global-container">
            <div class="card login-form">
                <div class="card-body">
                    <h3 class="card-title text-center"> EPI Login </h3>
                    <div class="card-text">
                        <form asp-action="LoginUser" asp-controller="Authenticate">
                            <div class="form-group">
                                <label for="exampleInputEmail1"> User name </label>
                                <input class="form-control form-control-sm"
                                       asp-for="UserName">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Enter Password </label>
                                <input class="form-control form-control-sm" asp-for="Password">
                            </div>
                            <button type="submit" class="btn btn-primary btn-block"> Sign in </button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

FinalProject.UI/Views/Employee/CreateEmployee.cshtml
@model Core.Entity.Employee
<form asp-action="CreateEmployee" asp-controller="Employee">

    <div class="form-group">
        <input type="hidden" asp-for="Id" />
        <label asp-for="EmpName" for="exampleInputEmail1">Employee Name</label>
        <input type="text" asp-for="EmpName" class="form-control" aria-describedby="emailHelp" placeholder="Enter Employee Name">
        <span asp-validation-for="EmpName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="EmpCode" for="exampleInputEmail1">Employee Code</label>
        <input type="text" asp-for="EmpCode" class="form-control" aria-describedby="emailHelp" placeholder="Enter Employee Code">
        <span asp-validation-for="EmpCode" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Gender" for="exampleFormControlSelect1">Gender</label>
        <select asp-for="Gender" class="form-control">
            <option active>Male</option>
            <option>Female</option>
        </select>
    </div>

    <div class="form-group">
        <label asp-for="DepartmentName" for="exampleInputEmail1">Department Name</label>
        <input type="text" asp-for="DepartmentName" class="form-control" aria-describedby="emailHelp" placeholder="Enter Department Name">
        <span asp-validation-for="DepartmentName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Salary" for="exampleInputEmail1">Salary</label>
        <input type="number" asp-for="Salary" class="form-control" aria-describedby="emailHelp" placeholder="Enter Salary">
        <span asp-validation-for="Salary" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="EmpImage" for="exampleInputEmail1">Employee Image</label>
        <input type="file" asp-for="EmpImage" class="form-control" aria-describedby="emailHelp">
        <span asp-validation-for="EmpImage" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

FinalProject.UI/Views/Employee/EmployeeList.cshtml
@model IEnumerable<Core.Entity.Employee>

<script><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"/></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<table class="table" style="border:solid">
    <thead>
        <tr>
            <th>
                Employee Name
            </th>
            <th>
                Employee Code
            </th>
            <th>
                Gender
            </th>
            <th>
                Department Name
            </th>
            <th>
                Salary
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model)
        {
            <tr>
                <td>
                    @data.EmpName
                </td>
                <td>
                    @data.EmpCode
                </td>
                <td>
                    @data.Gender
                </td>
                <td>
                    @data.DepartmentName
                </td>
                <td>
                    @data.Salary
                </td>
                <td>
                    <button onclick="DeleteRecord(@data.Id)" class="btn btn-danger">DELETE</button>
                </td>
                <td>
                    <a asp-controller="Employee" asp-action="Index" asp-route-id="@data.Id" class="btn btn-primary">Update</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    function DeleteRecord(Id) {
        if (confirm("Are you sure to delete this entry?")) {
            $.get("/Employee/DeleteEmployee", { Id: Id }, function (response) {
                if (response) {
                    alert("Record deleted Successfully!!!");
                    location.reload();
                }
                else {
                    alert("Unable to delete the record, Please contact admin.");
                }
            });
        }
    }
</script>

FinalProject.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FinalProject.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalProject.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinalProject.UI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserDetail" asp-action="Index">New User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FinalProject.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>